/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package habitpanel;

/**
 *
 * @author Emanuel
 */
public class HabitCard extends javax.swing.JPanel {

    
    public HabitCard(String habitNameInput) {
        initComponents();
        habitName.setText(habitNameInput);
        
        completedButton.setText("Not Done");
        completedButton.setBackground(new java.awt.Color(200,200,200));
        
        completedButton.addActionListener(e -> {
        if (completedButton.isSelected()) {
            completedButton.setText("Completed");
            completedButton.setBackground(new java.awt.Color(100,200,100));
        } else {
            completedButton.setText("Not Done");
            completedButton.setBackground(new java.awt.Color(200,200,200));
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        setMaximumSize(new java.awt.Dimension(237, 237));
        setMinimumSize(new java.awt.Dimension(237, 237));
        setPreferredSize(new java.awt.Dimension(237, 237));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Habit Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(237, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(237, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(237, 100));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jToggleButton1.setText("Completed");
        jToggleButton1.setMargin(new java.awt.Insets(2, 50, 3, 50));
        jToggleButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        add(jToggleButton1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
